openapi: 3.0.3
info:
  version: 1.0.0
  title: RDI Portal API
  contact:
    name: Contact our support
    email: hello@reldyn.co
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: >
    Included below are the API Endpoints available within the Reldyn Identity (RDI) Portal API. <br><br>
    There are many OpenAPI Tools available for you to work directly with the OpenAPI Specification, if desired. For instance, you may leverage code generation tools to generate client libraries in any one of the support languages and frameworks.
  x-logo:
    url: "https://reldyn.co/assets/images/logo.svg"
    backgroundColor: "#ee0979"
    altText: "Reldyn"
servers:
  - url: https://5yhs323cfd.execute-api.ap-south-1.amazonaws.com/platform
    description: Development server
tags:
  - name: Authentication
    description: API for obtaining OAuth 2.0 tokens using password grant.
  - name: Admins
    description: The API allows you to view and manage the organizations.
  - name: Collaborations
    description: The API allows you to view account's collaborations.
  - name: Requests
    description: The API allows you to view requests.
  - name: Reasons
    description: The API allows you to view and manage reasons.
