openapi: 3.0.3
info:
  title: Verification Service API
  description: |
    The API is based on REST principles. It uses standard HTTP response codes and verbs, and token-based authentication.
    All requests must be made over HTTPS with TLS 1.2+ and Server Name Indication enabled. HTTP requests over HTTP will fail.

    ## Base URL
    ```
    https://TENANT_NAME.reldynidentity.com/api
    ```
    Replace `TENANT_NAME` with your tenant name from the Identity Platform Dashboard tenant URL.

    ## HTTP Verbs
    - **GET**: Retrieve a resource or collection of resources
    - **POST**: Create a resource
    - **PATCH**: Modify an existing resource
    - **PUT**: Replace an existing resource
    - **DELETE**: Delete a resource

    ## Request and Response Format
    - Use `Content-Type: application/json` for all PUT and POST requests (except when uploading documents or live photos, in which case, use `Content-Type: multipart/form-data`).
    - Responses return JSON, except for downloads.
    - Text fields support UTF-8 encoding but certain special characters are not allowed.
  version: 1.0.0
  x-logo:
    url: 'https://reldyn.co/assets/images/logo.svg'
    backgroundColor: '#ee0979'
    altText: Reldyn
servers:
  - url: https://5yhs323cfd.execute-api.ap-south-1.amazonaws.com/api
    description: API server
    variables:
      tenant_name:
        default: TENANT_NAME
        description: Replace with the tenant name in your Identity Platform Dashboard URL.
paths:
  /api/v1/verifications:
    post:
      summary: Create a verification request
      description: |
        Creates a new verification request using customer details and metadata.
      operationId: createVerification
      tags:
        - Verification
      parameters:
        - in: header
          name: X-API-KEY
          required: true
          schema:
            type: string
      requestBody:
        description: Payload to create a verification request
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VerificationRequest'
      responses:
        '201':
          description: Verification request created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VerificationResponse'
        '400':
          description: Invalid request payload
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /api/v1/verifications/{request_reference}:
    get:
      summary: Retrieve verification status
      description: Get the current status and details of a verification request.
      operationId: getVerification
      tags:
        - Verification
      parameters:
        - in: header
          name: X-API-KEY
          required: true
          schema:
            type: string
        - in: path
          name: request_reference
          required: true
          schema:
            type: string
          description: Unique reference of the verification request
          example: 96a998ba-195c-4e3b-b3f2-7850e64dd376
        - in: query
          name: details_level
          required: false
          schema:
            type: string
            enum:
              - BASIC
              - FULL
            default: BASIC 
          description: Specify the level of details to return; BASIC returns summary only, FULL returns summary and results.
      responses:
        '200':
          description: Verification status retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VerificationStatusResponse'
        '400':
          description: Invalid request payload
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /api/v1/verifications/{request_reference}/files:
    get:
      summary: List all files of a request
      description: List all files associated with a specific request execution.
      operationId: listRequestFiles
      tags:
        - Verification
      parameters:
        - in: header
          name: X-API-KEY
          required: true
          schema:
            type: string
        - in: path
          name: request_reference
          required: true
          schema:
            type: string
          description: Unique identifier of the verification request
          example: a1b2c3d4-e5f6-7890-1234-567890abcdef
      responses:
        '200':
          description: List of files retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/VerificationRequestFileDto'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /api/v1/verifications/{request_reference}/files/{file_id}/download:
    get:
      summary: Download file of a request
      description: Download file associated with the request.
      operationId: downloadRequestFile
      tags:
        - Verification
      parameters:
        - in: header
          name: X-API-KEY
          required: true
          schema:
            type: string
        - in: path
          name: request_reference
          required: true
          schema:
            type: string
          description: Unique identifier of the verification request
          example: a1b2c3d4-e5f6-7890-1234-567890abcdef
        - in: path
          name: file_id
          required: true
          schema:
            type: string
          description: Unique reference of the file
          example: dd43ee6b-d90e-41b8-bb9b-385529d591fd
      responses:
        '200':
          description: File downloaded successfully
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
        '400':
          description: Invalid request payload
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /api/v1/verifications/{request_reference}/attempts:
    post:
      summary: Re-attempt a verification request
      description: Re-attempt a previously failed or incomplete verification request.
      operationId: reattemptVerificationRequest
      tags:
        - Verification
      parameters:
        - in: header
          name: X-API-KEY
          required: true
          schema:
            type: string
          description: API key for authentication.
        - in: path
          name: request_reference
          required: true
          schema:
            type: string
          description: Unique reference of the verification request.
          example: 96a998ba-195c-4e3b-b3f2-7850e64dd376
      responses:
        '201':
          description: Verification request created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VerificationResponse'
        '400':
          description: Invalid request payload
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    VerificationRequest:
      type: object
      required:
        - app
        - customer_internal_reference
        - purpose
      properties:
        app:
          type: string
          description: App for verification (currently supports ONFIDO and JUMIO)
          example: ONFIDO
        customer_internal_reference:
          type: string
          description: Channel customer ID
          example: f60a954e-fe14-4918-abbf-6d48ca71996c
        purpose:
          type: string
          description: Purpose of the request
          example: "QSA_NEW_APPLICATION"
        metadata:
          type: object
          properties:
            applicant_id:
              type: string
              description: If populated, will skip applicant creation
              example: 3993afe2-e4f1-4087-ab34-27edcac98ab0
            workflow_custom_input:
              type: object
              description: Additional custom input fields for the workflow, dynamically populated and sent to Onfido if not empty
              additionalProperties:
                type: object
              example:
                full_name: "Mohammed Faris"
                id_number: "860303-10-7491"
    VerificationResponse:
      type: object
      properties:
        status:
          type: string
          description: Status of the request
          enum:
            - PROCESSING
            - AWAITING_INPUT
            - REVIEW
            - APPROVED
            - DECLINED
            - ERROR
            - EXPIRED
            - BLOCKED
          example: PROCESSING
        reasons:
          type: array
          items:
            type: String
          description : List of reasons for declined status
          example: SIMILARITY_SCORE_BELOW_THRESHOLD
        created_at:
          type: string
          format: date-time
          description: Timestamp when the request was created
          example: '2022-06-28T15:39:42Z'
        request_reference:
          type: string
          description: Unique reference for querying request status
          example: 3993afe2-e4f1-4087-ab34-27edcac98ab0
        credentials:
          type: array
          description: Credentials for SDK initialization
          items:
            type: object
            properties:
              type:
                type: string
                description: Type of credential
                enum:
                  - ONFIDO_SDK_TOKEN
                  - ONFIDO_WORKFLOW_RUN_ID
                  - ONFIDO_APPLICANT_ID
                  - ONFIDO_WEB_URL
                  - JUMIO_SDK_TOKEN
                  - JUMIO_APPLICANT_ID
                  - JUMIO_WEB_URL
                  - JUMIO_WORKFLOW_RUN_ID
                example: ONFIDO_SDK_TOKEN
              value:
                type: string
                description: Value of the credential
                example: sdk_token_value
    VerificationStatusResponse:
      type: object
      properties:
        status:
          type: string
          description: Status of the request
          enum:
            - PROCESSING
            - AWAITING_INPUT
            - REVIEW
            - APPROVED
            - DECLINED
            - ERROR
            - EXPIRED
            - BLOCKED
          example: AWAITING_INPUT
        reasons:
          type: array
          items:
            type: String
          description: List of reasons for declined status
        request_reference:
          type: string
          description: Unique reference of the verification request
          example: 3993afe2-e4f1-4087-ab34-27edcac98ab0
        attempt_left:
          type: integer
          description: Number of attempts left for this request
          example: 3
        created_at:
          type: string
          format: date-time
          description: Timestamp when the request was created
          example: '2022-06-28T15:39:42Z'
        updated_at:
          type: string
          format: date-time
          description: Timestamp when the request was last updated
          example: '2022-07-28T15:40:42Z'
        metadata:
          type: object
          description: Metadata of the verification request details
        results:
          type: object
          description: Results, populated when status is BLOCKED, APPROVED, or DECLINED
        profile:
          type: object
          description: Profile of the applicant
          properties:
            type:
              type: string
              description: Ekyc card type
              enum:
                - NATIONAL_ID
                - RESIDENCE_PERMIT
                - MILITARY_ID
                - PASSPORT
                - DRIVING_LICENSE
                - UNSUPPORTED
                - OTHERS
              example: NATIONAL_ID
            id_number:
              type: string
              description: Document id number
              example: "660320101988"
            issuing_country:
              type: string
              description: Document issuing country
              example: MYS
            full_name:
              type: string
              description: Document full name
              example: Alexandra Avando
            first_name:
              type: string
              description: Document first name
              example: Avando
            middle_name:
              type: string
              description: Document middle name
              example: Alexandra
            last_name:
              type: string
              description: Document last name
              example: Alexandra
            full_address:
              type: string
              description: Document full address
              example: 88, jalan gembira, taman bahagia, 88888, selangor.
            address_line_1:
              type: string
              description: Document address line 1
              example: 88, jalan gembira
            address_line_2:
              type: string
              description: Document address line 2
              example: taman bahagia
            address_line_3:
              type: string
              description: Document address line 3
              example: 88888, selangor
            address_line_4:
              type: string
              description: Document address line 4
              example: t88888, selangor
            address_line_5:
              type: string
              description: Document address line 5
              example: 88888, selangor
            postcode:
              type: string
              description: Document address postal code
              example: "88888"
            city:
              type: string
              description: Document address city
              example: Klang
            state:
              type: string
              description: Document address state
              example: selangor
            country:
              type: string
              description: Document address country
              example: MYS
            gender:
              type: string
              description: Document gender
              example: M
            nationality:
              type: string
              description: Document nationality
              example: MY
            date_of_birth:
              type: string
              description: Document date of birth
              example: yyyy-MM-dd
    ErrorResponse:
      type: object
      properties:
        error_code:
          type: string
          description: Unique error code
          example: INVALID_REQUEST_REFERENCE
        error_reason:
          type: string
          description: Explanation of the error
          example: The provided request reference does not exist.
        timestamp:
          type: string
          format: date-time
          description: Timestamp when the result response returned
          example: '2022-06-28T15:39:42Z'
    VerificationRequestFileDto:
      type: object
      properties:
        id:
          type: string
          description: Unique identifier for the file
          example: d6f7ab5f-43c6-433d-98cc-dd253acb21a3
        category:
          type: string
          description: Category of the file
          example: ID
        sub_category:
          type: string
          description: Subcategory of the file
          example: FRONT
        file_name:
          type: string
          description: The name of the file
          example: file1.png
        file_type:
          type: string
          description: The type of the file (e.g., png, jpg)
          example: png
        file_size:
          type: integer
          description: The size of the file
          example: 88888