openapi: 3.0.3
info:
  title: RDI Verification Service API
  description: |
    The API is based on REST principles. It uses standard HTTP response codes and verbs, and token-based authentication.
    All requests must be made over HTTPS with TLS 1.2+ and Server Name Indication enabled. HTTP requests over HTTP will fail. 

    ## Base URL
    ```
    https://TENANT_NAME.reldyn.dev/api
    ```
    Replace `TENANT_NAME` with your tenant name from the Identity Platform Dashboard tenant URL.

    ## HTTP Verbs
    - **GET**: Retrieve a resource or collection of resources
    - **POST**: Create a resource
    - **PATCH**: Modify an existing resource
    - **PUT**: Replace an existing resource
    - **DELETE**: Delete a resource

    ## Request and Response Format
    - Use `Content-Type: application/json` for all PUT and POST requests (except when uploading documents or live photos, in which case, use `Content-Type: multipart/form-data`).
    - Responses return JSON, except for downloads.
    - Text fields support UTF-8 encoding but certain special characters are not allowed.
  version: 1.0.0
  x-logo:
    url: "https://reldyn.co/assets/images/logo.svg"
    backgroundColor: "#ee0979"
    altText: Reldyn
servers:
  - url: https://{tenant_name}.reldyn.dev/api
    description: API server
    variables:
      tenant_name:
        default: TENANT_NAME
        description: Replace with the tenant name in your Identity Platform Dashboard URL.
paths:
  /v1/verifications:
    post:
      summary: Create a verification request
      description: |
        Creates a new verification request using customer details and metadata.
        Requires a Bearer token for authorization.
      operationId: createVerification
      tags:
        - Verification
      security:
        - BearerAuth: []
      requestBody:
        description: Payload to create a verification request
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/VerificationRequest"
      responses:
        "201":
          description: Verification request created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/VerificationResponse"
        "400":
          description: Invalid request payload
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
  /v1/verifications/{request_reference}:
    get:
      summary: Retrieve verification status
      description: Get the current status and details of a verification request.
      operationId: getVerification
      tags:
        - Verification
      security:
        - BearerAuth: []
      parameters:
        - in: path
          name: request_reference
          required: true
          schema:
            type: string
          description: Unique reference of the verification request
          example: request_123
        - in: query
          name: details_level
          required: true
          schema:
            type: string
            enum:
              - BASIC
              - FULL
          description: Specify the level of details to return; BASIC returns summary only, FULL returns summary and results.
      responses:
        "200":
          description: Verification status retrieved successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/VerificationStatusResponse"
        "400":
          description: Invalid request payload
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
  /v1/verifications/{request_reference}/download:
    post:
      summary: Download a document
      description: |
        Downloads a document associated with the verification request using the provided service and object's value ID.
      operationId: downloadDocument
      tags:
        - Verification
      security:
        - BearerAuth: []
      parameters:
        - in: path
          name: request_reference
          required: true
          schema:
            type: string
          description: Unique reference of the verification request
          example: request_123
      requestBody:
        description: Payload to download a document
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DocumentDownloadRequest"
      responses:
        "200":
          description: Document downloaded successfully
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
        "400":
          description: Invalid request payload
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    VerificationRequest:
      type: object
      required:
        - services
      properties:
        services:
          type: string
          description: Services for verification (currently only supports ONFIDO)
          example: ONFIDO
        customer_internal_reference:
          type: string
          description: Channel customer ID
          example: customer_123
        metadata:
          type: object
          properties:
            workflow_id:
              type: string
              description: Workflow ID (mandatory for ONFIDO)
              example: workflow_123
            applicant_id:
              type: string
              description: If populated, will skip applicant creation
              example: applicant_123

    VerificationResponse:
      type: object
      properties:
        status:
          type: string
          description: Status of the request
          enum:
            - PENDING
            - PROCESSING
            - REVIEW
            - APPROVED
            - DECLINED
            - ERROR
            - EXPIRED
          example: PENDING
        reason:
          type: string
          description: Reason for declined status
          example: SIMILARITY_SCORE_BELOW_THRESHOLD
        created_at:
          type: string
          format: date-time
          description: Timestamp when the request was created
          example: "2022-06-28T15:39:42Z"
        request_reference:
          type: string
          description: Unique reference for querying request status
          example: request_123
        credentials:
          type: array
          description: Credentials for SDK initialization
          items:
            type: object
            properties:
              type:
                type: string
                description: Type of credential
                enum:
                  - ONFIDO_SDK_TOKEN
                  - ONFIDO_WORKFLOW_RUN_ID
                  - ONFIDO_APPLICANT_ID
                example: ONFIDO_SDK_TOKEN
              value:
                type: string
                description: Value of the credential
                example: sdk_token_value
    VerificationStatusResponse:
      type: object
      properties:
        status:
          type: string
          description: Status of the request
          enum:
            - PENDING
            - PROCESSING
            - REVIEW
            - APPROVED
            - DECLINED
            - ERROR
            - EXPIRED
          example: DECLINED
        reason:
          type: string
          nullable: true
          description: Reason for declined status
          example: SIMILARITY_SCORE_BELOW_THRESHOLD
        request_reference:
          type: string
          description: Unique reference of the verification request
          example: request_123
        created_at:
          type: string
          format: date-time
          description: Timestamp when the request was created
          example: "2022-06-28T15:39:42Z"
        updated_at:
          type: string
          format: date-time
          description: Timestamp when the request was last updated
          example: "2022-07-28T15:40:42Z"
        summary:
          type: array
          description: Summary of the verification request details
          items:
            type: object
            properties:
              service:
                type: string
                description: Name of the service (e.g., ONFIDO)
                example: ONFIDO
              created_at:
                type: string
                format: date-time
                description: When the summary was created
                example: "2022-06-28T15:39:42Z"
              updated_at:
                type: string
                format: date-time
                description: When the summary was last updated
                example: "2022-07-28T15:39:52Z"
              value:
                type: object
                description: Dynamic key-value pairs for the summary
                additionalProperties: true
        results:
          type: array
          description: Results, populated when status is REVIEW, APPROVED, or DECLINED
          items:
            type: object
            properties:
              service:
                type: string
                description: Name of the service (e.g., ONFIDO)
                example: ONFIDO
              created_at:
                type: string
                format: date-time
                description: When the result was created
                example: "2022-06-28T15:39:42Z"
              updated_at:
                type: string
                format: date-time
                description: When the result was last updated
                example: "2022-07-28T15:39:52Z"
              values:
                type: array
                description: Dynamic key-value pairs based on the service
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      description: Identifier for the dynamic property
                      example: document_check_eb954
                    value:
                      type: object
                      description: Dynamic key-value pairs for the result
                      additionalProperties: true
    DocumentDownloadRequest:
      type: object
      required:
        - service
        - value_id
      properties:
        service:
          type: string
          description: Name of the service for the document
          example: ONFIDO
        value_id:
          type: string
          description: Unique identifier for the object to be downloaded
          example: "123"
    ErrorResponse:
      type: object
      properties:
        error_code:
          type: string
          description: Unique error code
          example: INVALID_REQUEST_REFERENCE
        error_reason:
          type: string
          description: Explanation of the error
          example: The provided request reference does not exist.
